export const ADD_SERVICE = 'ADD_SERVICE';
export const SHOW_SERVICE_DETAILS = 'SHOW_SERVICE_DETAILS';
export const OPEN_FILE = 'OPEN_FILE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_ENV_VARIABLE = 'UPDATE_ENV_VARIABLE';
export const ADD_ENV_VARIABLE = 'ADD_ENV_VARIABLE';
export const DELETE_ENV_VARIABLE = 'DELETE_ENV_VARIABLE';
export const IMPORT_COMPOSE_FILE = 'IMPORT_COMPOSE_FILE';
